### ISSUE TITLE
Does not see DVI monitors

### ISSUE THREAD

**Issue by iconoclasthero** [MestreLion/scripts#4]
Saw your [post](https://stackoverflow.com/questions/10500521/linux-retrieve-monitor-names) and decided to give your script a try.  It does not see my either of my primary monitors, one of which is the display BIOS/GRUB shows on.

```
$ monitor-switch --list
Connected monitors:
# DP-0	DisplayPort	S22B300
# HDMI-0	HDMI	DELL E2414H

$ grep NVIDIA /var/log/Xorg.0.log
[519989.444] (--) NVIDIA(GPU-0): CRT-0: disconnected
[519989.444] (--) NVIDIA(GPU-0): CRT-0: 400.0 MHz maximum pixel clock
[519989.444] (--) NVIDIA(GPU-0): 
[519989.489] (--) NVIDIA(GPU-0): HYO DUAL-DVI (DFP-0): connected
[519989.489] (--) NVIDIA(GPU-0): HYO DUAL-DVI (DFP-0): Internal TMDS
[519989.489] (--) NVIDIA(GPU-0): HYO DUAL-DVI (DFP-0): 330.0 MHz maximum pixel clock
[519989.489] (--) NVIDIA(GPU-0): 
[519989.495] (--) NVIDIA(GPU-0): DELL E2414H (DFP-1): connected
[519989.496] (--) NVIDIA(GPU-0): DELL E2414H (DFP-1): Internal TMDS
[519989.496] (--) NVIDIA(GPU-0): DELL E2414H (DFP-1): 165.0 MHz maximum pixel clock
[519989.496] (--) NVIDIA(GPU-0): 
[519989.525] (--) NVIDIA(GPU-0): Samsung S22B300 (DFP-2): connected
[519989.525] (--) NVIDIA(GPU-0): Samsung S22B300 (DFP-2): Internal TMDS
[519989.525] (--) NVIDIA(GPU-0): Samsung S22B300 (DFP-2): 165.0 MHz maximum pixel clock
[519989.525] (--) NVIDIA(GPU-0): 
[519989.548] (--) NVIDIA(GPU-0): HYO DUAL-DVI (DFP-3): connected
[519989.548] (--) NVIDIA(GPU-0): HYO DUAL-DVI (DFP-3): Internal TMDS
[519989.548] (--) NVIDIA(GPU-0): HYO DUAL-DVI (DFP-3): 330.0 MHz maximum pixel clock
[519989.548] (--) NVIDIA(GPU-0): 
[519989.548] (--) NVIDIA(GPU-0): DFP-4: disconnected
[519989.548] (--) NVIDIA(GPU-0): DFP-4: Internal DisplayPort
[519989.548] (--) NVIDIA(GPU-0): DFP-4: 960.0 MHz maximum pixel clock
[519989.548] (--) NVIDIA(GPU-0): 
[519989.565] (II) NVIDIA(0): Setting mode "DVI-I-1: nvidia-auto-select @2560x1440 +4480+0 {ViewPortIn=2560x1440, ViewPortOut=2560x1440+0+0}, HDMI-0: nvidia-auto-select @1920x1080 +7040+0 {ViewPortIn=1920x1080, ViewPortOut=1920x1080+0+0}, DP-0: nvidia-auto-select @1920x1080 +2560+0 {ViewPortIn=1920x1080, ViewPortOut=1920x1080+0+0}, DVI-D-0: nvidia-auto-select @2560x1440 +0+0 {ViewPortIn=2560x1440, ViewPortOut=2560x1440+0+0}
```

**Comment by MestreLion** [comment]
Care to post the output of `xrandr --prop`? Maybe there's something non-standard in their EDID blocks.

By the way, you don't _need_ monitor detection to use `monitor-switch` (or `monitor-rotate`): they both operate on output _names_, as reported by `xrandr --prop`. Judging by your log,  yours _seems_ to be `DFP-0`, `DFP-1`, `DFP-2` and `DFP-3`. 

And man... 4 monitors, wow! Congrats on that setup!

**Comment by iconoclasthero** [comment]
xrandr --prop:  https://pastebin.com/iijs8k1W
Well, I was actually looking for listing monitors.  I'm having a set of problems that I can't figure out relating to one of the HYO monitors in portrait right.
Is DFP just a legacy term for digital flat panel that has nothing to do with the actual interface used on the card?

Also, I checked apt log after posting this and low and behold at 5 this morning:

`Upgrade: libseccomp2:amd64 (2.4.3-1ubuntu3.20.04.3, 2.5.1-1ubuntu1~20.04.1), libnvidia-compute-460:amd64 (460.39-0ubuntu0.20.04.1, 460.56-0ubuntu0.20.04.1), libnvidia-compute-460:i386 (460.39-0ubuntu0.20.04.1, 460.56-0ubuntu0.20.04.1), libnvidia-encode-460:amd64 (460.39-0ubuntu0.20.04.1, 460.56-0ubuntu0.20.04.1), libnvidia-encode-460:i386 (460.39-0ubuntu0.20.04.1, 460.56-0ubuntu0.20.04.1), nvidia-kernel-common-460:amd64 (460.39-0ubuntu0.20.04.1, 460.56-0ubuntu0.20.04.1), xserver-xorg-video-nvidia-460:amd64 (460.39-0ubuntu0.20.04.1, 460.56-0ubuntu0.20.04.1), libnvidia-gl-460:amd64 (460.39-0ubuntu0.20.04.1, 460.56-0ubuntu0.20.04.1), libnvidia-gl-460:i386 (460.39-0ubuntu0.20.04.1, 460.56-0ubuntu0.20.04.1), libnvidia-fbc1-460:amd64 (460.39-0ubuntu0.20.04.1, 460.56-0ubuntu0.20.04.1), libnvidia-fbc1-460:i386 (460.39-0ubuntu0.20.04.1, 460.56-0ubuntu0.20.04.1), libnvidia-decode-460:amd64 (460.39-0ubuntu0.20.04.1, 460.56-0ubuntu0.20.04.1), libnvidia-decode-460:i386 (460.39-0ubuntu0.20.04.1, 460.56-0ubuntu0.20.04.1), google-chrome-stable:amd64 (89.0.4389.114-1, 90.0.4430.72-1), libjs-underscore:amd64 (1.9.1~dfsg-1, 1.9.1~dfsg-1ubuntu0.20.04.1), libnvidia-cfg1-460:amd64 (460.39-0ubuntu0.20.04.1, 460.56-0ubuntu0.20.04.1), nvidia-utils-460:amd64 (460.39-0ubuntu0.20.04.1, 460.56-0ubuntu0.20.04.1), picard:amd64 (2.6-1+git3910~ppa23~ubuntu20.04.1, 2.6-1+git3914~ppa23~ubuntu20.04.1), nvidia-dkms-460:amd64 (460.39-0ubuntu0.20.04.1, 460.56-0ubuntu0.20.04.1), nvidia-compute-utils-460:amd64 (460.39-0ubuntu0.20.04.1, 460.56-0ubuntu0.20.04.1), libnvidia-ifr1-460:amd64 (460.39-0ubuntu0.20.04.1, 460.56-0ubuntu0.20.04.1), libnvidia-ifr1-460:i386 (460.39-0ubuntu0.20.04.1, 460.56-0ubuntu0.20.04.1), nvidia-driver-460:amd64 (460.39-0ubuntu0.20.04.1, 460.56-0ubuntu0.20.04.1), code:amd64 (1.55.1-1617808414, 1.55.2-1618307277), pciutils:amd64 (1:3.6.4-1, 1:3.6.4-1ubuntu0.20.04.1), libnvidia-common-460:amd64 (460.39-0ubuntu0.20.04.1, 460.56-0ubuntu0.20.04.1), libpci3:amd64 (1:3.6.4-1, 1:3.6.4-1ubuntu0.20.04.1), libpci3:i386 (1:3.6.4-1, 1:3.6.4-1ubuntu0.20.04.1), libnvidia-extra-460:amd64 (460.39-0ubuntu0.20.04.1, 460.56-0ubuntu0.20.04.1), nvidia-kernel-source-460:amd64 (460.39-0ubuntu0.20.04.1, 460.56-0ubuntu0.20.04.1)
`

Maybe after reboot and the kernel is updated it will solve the issue w/the script.

**Comment by MestreLion** [comment]
Yeah, those are a bunch of video-related updates.  But I doubt it will change the way monitors report their EDID data to `xrandr`. I'll analyze your data to see if this is a parsing error or malformed EDID, thanks for reporting! What I tell say up-front is that it's really weird for the EDID of the DVI (and DP) monitors to be padded with `FF` instead of 0, making them twice as as long as the standard ones.

**Comment by MestreLion** [comment]
> Is DFP just a legacy term for digital flat panel that has nothing to do with the actual interface used on the card?

Yup. It's been a few years (5?) since `xrand` changed its naming from `DFP` to more meaningful ones. It started really verbose (mine are `DisplayPort-X`), and I'm glad they seem to have changed to `DP-X`.

In any case, these are all just labels. To check the actual connector they're using, see the `ConnectorType` that `xrandr` reports for each connected monitor, which is also parsed and displayed by `monitor-switch --list`

**Comment by iconoclasthero** [comment]
Rebooting did not change the output of monitor-switch but it did restore the GPU which was missing from screenfetch -n:

```
No value set for `/apps/metacity/general/theme'
 
 OS: Ubuntu 20.04 focal
 Kernel: x86_64 Linux 5.8.0-48-generic
 Uptime: 1m
 Packages: 2588
 Shell: bash 5.0.17
 Resolution: 7840x2560
 DE: GNOME 3.36.5
 WM: Metacity
 GTK Theme: Yaru [GTK2/3]
 Icon Theme: ubuntu-mono-light
 Font: Ubuntu 11
 Disk: 3.0T / 3.7T (85%)
 CPU: Intel Core i5-3570K @ 4x 3.8GHz [38.0°C]
 GPU: GeForce GTX 650 Ti BOOST
 RAM: 4330MiB / 24013MiB

```

**Comment by MestreLion** [comment]
Was this file you pasted somehow processed in a windows machine or something? I spend the last hours struggling with `awk`'s print output exhibiting a really weird behavior, just to find out the file is using DOS line-endings (i.e, CRLF `\r\n` instead of `\n`), and this really messed the parser. Maybe `pastebin` is adding them?

**Comment by MestreLion** [comment]
Found the bug(s)!

The EDID of all of your DVI monitors contain 2 `000000fc00` "entries", one of them with the monitor name (just like all other monitors), and an extra, empty one.

Since my `awk` parser is using an eager regex, it is only considering the last entry so the empty string is assigned as monitor name. Additionally, my script do not list any monitor without a name, so it is skipping over those with blank names. 2 distinct bugs, both soon to be fixed.

**Comment by iconoclasthero** [comment]
It definitely did not get processed on Windows/DOS/Power Shell...
I went to the raw section of the code, copied and pasted into nano, saved
to ~/bin and chmod u+x.

**Comment by MestreLion** [comment]
> Was this file you pasted somehow processed in a windows machine or something?

>> It definitely did not get processed on Windows/DOS/Power Shell... I went to the raw section of the code, copied and pasted into nano, saved to ~/bin and chmod u+x.

You're talking about how you created ***your*** `monitor-switch`, right? I was referring to how you _generated_ and uploaded  https://pastebin.com/iijs8k1W. Somewhere in the process the Unix LF line-endings were converted to CRLF, which broke ***my*** `monitor-switch` when trying to analyze your data. It's quite possible pastebin website added the pesky `\r` when I selected downloaded. Anyway, I've added a `tr -d '\r' |` safeguard to the pipeline to avoid this in the future.

**Comment by MestreLion** [comment]
About the bugs themselves: It seems changing `awk` to use non-greedy regex is way trickier than I first assumed, so it might take a while for me to fix it. But I'll soon push a partial fix so it at least displays the outputs even if the names are blank (which will be your case)

**Comment by MestreLion** [comment]
Here's the result of the new parser on your data:

```
# DP-0	DisplayPort	S22B300
# DVI-D-0	DVI-D	
# DVI-I-1	DVI-I	
# HDMI-0	HDMI	DELL E2414H
```

Still missing the names, but at least now showing all connected outputs

**Comment by iconoclasthero** [comment]
Yeah, no...  I don't have anything that presently runs Windows...  I wish I did because I can't set this damn printer up on the wifi without windows. But your assessment that it happened w/pastebin is probably right.  There's a "raw" tab from the first link that might be the better place to pull from:  https://pastebin.com/raw/iijs8k1W.  Actually, give that a try if you get a chance, I'm curious.

Hey, you're obviously one who loves a challenge...and enjoys finding the bug.  I'm grateful you're taking the time.  ([Make America Grateful Again](https://res.cloudinary.com/teepublic/image/private/s--KMAUyZQa--/t_Preview/b_rgb:006cb5,c_limit,f_auto,h_630,q_90,w_630/v1615364652/production/designs/20090652_0.jpg)!)

Yes, those are the right two DVI monitors.  I'm in gnome-control-settings and it lists the DVIs as "HYC CO., LTD. 27""

You're in Rio?  Stay safe.

**Comment by MestreLion** [comment]
> But your assessment that it happened w/pastebin is probably right. There's a "raw" tab from the first link that might be the better place to pull from: https://pastebin.com/raw/iijs8k1W. Actually, give that a try if you get a chance, I'm curious.

Yup, it **is** inserting `\r` in that raw URL too, just checked using my `whitespace` [alias](../blob/main/home/bash_aliases). Not so "raw"  after all all, huh? Shame on you, Pastebin! Messing with file's newlines in both "download" and "Raw" tab! Now I understand why the Bash Gurus in Freenode always strongly advise against it.

**Comment by MestreLion** [comment]
> Hey, you're obviously one who loves a challenge...and enjoys finding the bug.

It's not so much about loving challenges... it's more about hating things that don't work.  If some code of mine is broken, I outta fix it.

> I'm grateful you're taking the time. ([Make America Grateful Again](https://res.cloudinary.com/teepublic/image/private/s--KMAUyZQa--/t_Preview/b_rgb:006cb5,c_limit,f_auto,h_630,q_90,w_630/v1615364652/production/designs/20090652_0.jpg)!)

Err... ok, I guess, whatever that means :)

> You're in Rio? Stay safe.

Born and raised here! And yeah, really sad what's going on here... Given our history and expertise in public healthcare and  huge mass vaccinations every year, we were supposed to be shining as an example to follow, not being the current epicenter of this virus. I never imagined a single president could do such a huge damage.

But anyway, thanks for caring... I'm trying my best to stay safe, social isolation was never a problem for me, lol.

**Comment by MestreLion** [comment]
> Yes, those are the right two DVI monitors. I'm in gnome-control-settings and it lists the DVIs as "HYC CO., LTD. 27""

So Gnome is also **not** reading monitor's _model names_... `HYC CO.` is the manufacturer, and 27" is the size.

I have good news and bad news for you:

- Good news is.. I've fixed the bug! Now I'm able to properly parse their model names. Will be pushing an updated version in a few minutes, try it out!

- Bad news is... the "model names" these monitors report are...
```
# DP-0	DisplayPort	S22B300
# DVI-D-0	DVI-D	DUAL-DVI
# DVI-I-1	DVI-I	DUAL-DVI
# HDMI-0	HDMI	DELL E2414H
```

So much trouble for such generic names!
