### ISSUE TITLE
[monitor-switch] - "-l" flag is defined twice (--list & --left)

### ISSUE THREAD

**Issue by ZereoX** [MestreLion/scripts#5]
Hi,

Would just like to mention that the "-l" flag is defined twice but only applicable for "--list". Changing the flag to anything else should resolve the issue "-ls" for example.

https://github.com/MestreLion/scripts/blob/fc864fed083471d2d0afe45ecff1f9d276349d11/monitor-switch#L177
https://github.com/MestreLion/scripts/blob/fc864fed083471d2d0afe45ecff1f9d276349d11/monitor-switch#L182

Thanks for the script. Has been super useful to make use of VariableRefresh on X11 by disabling the secondary monitor.

**Comment by MestreLion** [comment]
Wow, that's an embarrassing overlook! Thank you very much for spotting!

So, as a fix, what do you think about `-L` for left (and also changing right to `-R`  for consistency)?

**Comment by ZereoX** [comment]
> Wow, that's an embarrassing overlook! Thank you very much for spotting!
> 
> So, as a fix, what do you think about `-L` for left (and also changing right to `-R` for consistency)?

Yeah, that seems completely reasonable with me :)
